config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  resources :tasks
  get 'users/detail'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :blogs do
    resources :comments
    
    collection do
      post :confirm
    end
  end
  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end
  resources :users, only: [:index] do
    member do
      post :detail
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :submit_requests do
    get 'inbox', on: :collection
    member do
      patch 'approve'
      patch 'reject'
    end
  end
  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'top#index'

end

app/models/submit_request.rb
class SubmitRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
  belongs_to :request_user, class_name: 'User', foreign_key: 'request_user_id'
  
  validates :user_id, :task_id, :request_user_id, presence: true
  
  validate :no_repeated_request, on: :create
  
  #enum status: {依頼中:1, 承認済み:2, 依頼を却下:9}
  
  private
    def no_repeated_request
      submit_request = SubmitRequest.where(task_id: task_id, status: 1)
      errors.add(:base, "このタスクは既に依頼をだしています。") unless submit_request.blank?
    end  
  
end

app/controllers/submit_requests_controller.rb
class SubmitRequestsController < ApplicationController
  before_action :set_submit_request, only: [:show, :edit, :update, :destroy, :approve, :reject]
  before_action :authenticate_user!

  # GET /submit_requests
  # GET /submit_requests.json
  def index
    @submit_requests = SubmitRequest.where(user_id: current_user.id)
  end

  # GET /submit_requests/1
  # GET /submit_requests/1.json
  #def show
  #end

  # GET /submit_requests/new
  def new
    @submit_request = current_user.submit_requests.build
  end

  # GET /submit_requests/1/edit
  def edit
  end

  # POST /submit_requests
  # POST /submit_requests.json
  def create
    @submit_request = current_user.submit_requests.build(submit_request_params)

    respond_to do |format|
      if @submit_request.save
        format.html { redirect_to @submit_request, notice: 'タスク依頼を追加しました。' }
        format.json { render :show, status: :created, location: @submit_request }
      else
        format.html { render :new }
        format.json { render json: @submit_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submit_requests/1
  # PATCH/PUT /submit_requests/1.json
  def update
    respond_to do |format|
      if @submit_request.update(submit_request_params)
        format.html { redirect_to @submit_request, notice: 'Submit request was successfully updated.' }
        format.json { render :show, status: :ok, location: @submit_request }
      else
        format.html { render :edit }
        format.json { render json: @submit_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submit_requests/1
  # DELETE /submit_requests/1.json
  def destroy
    @submit_request.destroy
    respond_to do |format|
      format.html { redirect_to submit_requests_url, notice: 'Submit request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  #承認
  def approve
    if @submit_request.update(submit_request_params)
      @submit_request.task.update(charge_id: current_user.id)
      redirect_to inbox_submit_requests_path, notice: '依頼を承認しました。'
    else
      redirect_to inbox_submit_requests_path, notice: '不具合が発生しました。もう一度操作を行ってください。'
    end
  end
  
  #却下
  def reject
    if @submit_request.update(submit_request_params)
      redirect_to inbox_submit_requests_path, notice: '依頼を却下しました。'
    else
      redirect_to inbox_submit_requests_path, notice: '不具合が発生しました。もう一度操作を行ってください。'
    end
  end
  
  def inbox
    @submit_requests = SubmitRequest.where(request_user_id: current_user.id).where(status: 1)
  end

  private
    def set_submit_request
      @submit_request = SubmitRequest.find(params[:id])
    end

    def submit_request_params
      params.require(:submit_request).permit(:user_id, :task_id, :message, :request_user_id, :status)
    end
end

app/helpers/submit_requests_helper.rb
module SubmitRequestsHelper
    def change_status(status)
        case status
        when 1 then
            return '依頼中'
        when 2 then
            return '承認済'
        when 9 then
            return '依頼を却下'
        end    
    end
end

app/views/submit_requests/_form.html.erb
<%= form_for(@submit_request) do |f| %>
  <% if @submit_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submit_request.errors.count, "error") %> prohibited this submit_request from being saved:</h2>

      <ul>
      <% @submit_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% f.hidden_field :user_id %>

  <div class="field">
    <%= f.label :タスク %><br>
    <%= f.collection_select :task_id, Task.where(charge_id: current_user.id), :id, :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :メッセージ %><br>
    <%= f.text_area :message, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :依頼ユーザ %><br>
    <%= f.collection_select :request_user_id, User.where.not(id: current_user.id), :id, :name, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit '登録', class: 'btn btn-primary btn-block'%>
  </div>
<% end %>

app/views/submit_requests/edit.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <h1>タスク依頼を修正</h1>
        <%= render 'form' %>
        
        <%= link_to '照会', @submit_request, class: 'btn btn-default' %> |
        <%= link_to '戻る', submit_requests_path, class: 'btn btn-default' %>
    </div>
</div>

app/views/submit_requests/inbox.html.erb
<div class="container">
  <div class="wrapper col-md-10 col-md-offset-1 col-sm-10">
    <p id="notice"><%= notice %></p>
    
    <h1>受信タスク依頼一覧</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>依頼元ユーザ</th>
          <th>タスク</th>
          <th>メッセージ</th>
          <th>依頼先依頼ユーザ</th>
          <th>ステータス</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @submit_requests.each do |submit_request| %>
          <tr>
            <td><%= submit_request.user.name %></td>
            <td><%= submit_request.task.title %></td>
            <td><%= submit_request.message %></td>
            <td><%= submit_request.request_user.name %></td>
            <td><%= change_status(submit_request.status) %></td>
            <td><%= link_to '照会', submit_request %></td>
            <td><%= link_to '承認する', approve_submit_request_path(submit_request, submit_request: {status: 2}), method: :patch, data: { confirm: '承認しますか?' } %></td>
            <td><%= link_to '却下する', reject_submit_request_path(submit_request, submit_request: {status: 9}), method: :patch, data: { confirm: '却下しますか?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/submit_requests/index.html.erb
<div class="container">
  <div class="wrapper col-md-10 col-md-offset-1 col-sm-10">
    <p id="notice"><%= notice %></p>
    
    <h1>送信タスク依頼一覧</h1>
    <%= link_to 'タスク依頼', new_submit_request_path, class: 'btn btn-default' %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>依頼元ユーザ</th>
          <th>タスク</th>
          <th>メッセージ</th>
          <th>依頼先ユーザ</th>
          <th>ステータス</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @submit_requests.each do |submit_request| %>
          <tr>
            <td><%= submit_request.user.name %></td>
            <td><%= submit_request.task.title %></td>
            <td><%= submit_request.message %></td>
            <td><%= submit_request.request_user.name %></td>
            <td><%= change_status(submit_request.status) %></td>
            <td><%= link_to '照会', submit_request %></td>
            <td><%= link_to '修正', edit_submit_request_path(submit_request) %></td>
            <td><%= link_to '削除', submit_request, method: :delete, data: { confirm: '本当に削除していいですか?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/submit_requests/new.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <h1>タスク依頼</h1>
        
        <%= render 'form' %>
        <%= link_to '戻る', submit_requests_path, class: 'btn btn-default' %>
    </div>
</div>

app/views/submit_requests/show.html.erb
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <p id="notice"><%= notice %></p>
    <p class="left">
      <strong>ユーザ:</strong>
      <%= @submit_request.user.name %>
    </p>
    <p class="left">
      <strong>タスク:</strong>
      <%= @submit_request.task.title %>
    </p>
    <p class="left">
      <strong>メッセージ:</strong>
      <%= @submit_request.message %>
    </p>
    <p class="left">
      <strong>依頼したユーザ:</strong>
      <%= @submit_request.request_user_id %>
    </p>
    <p class="left">
      <strong>ステータス:</strong>
      <%= @submit_request.status %>
    </p>
    <%= link_to '修正', edit_submit_request_path(@submit_request), class: 'btn btn-default' %> |
    <%= link_to '戻る', submit_requests_path, class: 'btn btn-default' %>
  </div>
</div>